### ISSUE TITLE
Als PO wil ik de metrics uit de microservice gezag in de ELK stack integreren

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/brp-api-gezag#109]
zodat deze kunnen worden opgenomen in het dashboard van BRP API Personen

**Comment by FrozenSync** [comment]
Metrics zijn geïmplementeerd op basis van logging in plaats van een aparte metrics oplossing.

Implementatie is meegenomen in issue #117 .

**Comment by FrozenSync** [comment]
[ecs-logging-java](https://github.com/elastic/ecs-logging-java) support nog geen _structured logging_, wat onder andere het maskeren van PII mogelijk maakt. Zie [issue](https://github.com/elastic/ecs-logging-java/issues/49). Deze issue is al bijna 5 jaar oud, dus het lijkt er niet op dat hier een oplossing komt op korte termijn.
