### ISSUE TITLE
meerderjarige met RNI geen GezagNietTeBepalen geven

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#113]
In de data-service hadden we een wijziging ingebouwd die ervoor zorgt dat een meerderjarige in de RNI niet GezagNietTeBepalen krijgt. We weten dan namelijk wel dat niemand gezag over de persoon heeft.

Deze functionaliteit is nu weggevallen. N.m.m. moet dit worden hersteld.

Zie https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/master/features/bevragen/persoon/gezag/dev/gezag-meerderjarige-gba.feature vanaf regel 538

- Regel: een persoon die in RNI staat ingeschreven krijgt gezag niet te bepalen geleverd wanneer de leeftijd lager is dan 18 jaar
- Regel: een persoon die in RNI staat ingeschreven met een onvolledige geboortedatum krijgt gezag niet te bepalen geleverd wanneer het geboortejaar is ten minste 19 jaar voor het huidige jaar
- Regel: een persoon die in RNI staat ingeschreven krijgt gezag niet te bepalen geleverd wanneer de geboortedatum volledig onbekend is

**Comment by fsamwel** [comment]
@CathyDingemanse we willen deze functionaliteit behouden, toch? Moet dit dan verplaatst worden naar de gezag api of wil je dat dit versteld wordt in de personen-data-service?

**Comment by fsamwel** [comment]
hoe dan ook, deze feature moet worden aangepast, zodat de gegeven stappen leiden tot de juiste resultaten bij gebruik van de database ipv de oude gezag-mock

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse we willen deze functionaliteit behouden, toch? Moet dit dan verplaatst worden naar de gezag api of wil je dat dit versteld wordt in de personen-data-service?

A Ik begrijp dat we nu gezag niet te bepalen leveren, terwijl we niets moeten leveren omdat er niemand gezag heeft over de RNI persoon. Het gaat dan om een persoon zonder kinderen
Klopt dat? 
B Echter, als een persoon in de RNI staat en persoon heeft zelf kinderen, dan wordt gezag gewoon geleverd.

Jouw vraag gaat over A, klopt dat?
