### ISSUE TITLE
Verwijder de 11-proef uit gezag-api

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#114]
om sommige gevallen krijg ik in plaats van "gezag": [] helemaal geen gezag geleverd. 

Bijvoorbeeld Lg01_049 op de proefomgeving. In de feature in #3 krijg ik wel GezagNietTeBepalen, maar hetzelfde testgeval op de proefomgeving krijg ik niks. (ik ben er nog niet achter wat het verschil is in data tussen de RvIG proefomgeving en de feature)

**Comment by FrozenSync** [comment]
@fsamwel Klopt het dat het teruggeven antwoord `200 OK []` is? In dat geval is de burgerservicenummer niet door de ELF proef heen gekomen.

**Comment by fsamwel** [comment]
dat lijkt inderdaad de oorzaak. dat is wel onhandig, want blijkbaar voldoen niet alle testpersonen in de proefomgeving aan de 11-proef. In dit geval gaat het om een persoon die in de S&T test voorkomt.

Is er een belangrijke reden om de 11-proef in de gezag-api actief te houden? De gezag-app krijgt alleen requests met burgerservicenummers wanneer die burgerservicenummers al in de database gevonden zijn door de personen-api.
Vanuit security zou het denk ik genoeg zijn om vast te stellen dat het burgerservicenummer uit 9 cijfers bestaat.

**Comment by FrozenSync** [comment]
Als aangenomen kan worden dat personen-data-service alleen requests stuurt met valide burgerservicenummers, kan de 11-proef wat mij betreft eruit.

In het onwaarschijnlijke scenario dat de Kubernetes cluster gehackt is waardoor een hacker ongelimiteerde toegang heeft tot de gezag-app, valt er niks te winnen met het porren van gezag-app met invalide burgerservicenummers. In die zin hoeven we het niet te doen voor security, lijkt mij.

De enige toegevoegde waarde van de 11-proef is de gebruiker (personen-data-service) laten weten dat de burgerservicenummer invalide is. Volgens mij is hier geen behoefte naar, dus kan het eruit.
