### ISSUE TITLE
volgorde opgevoerde relaties onterecht bepalend voor bepalen reparatiehuwelijk

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#115]
Bijvoorbeeld Lg01_060 gaat nu goed. Hier wordt indicatie gezag genegeerd omdat er daarna reparatiehuwelijk is.

Maar wanneer de gegeven stappen in een andere volgorde worden opgesteld, met het reparatiehuwelijk eerst (stapel 0) en het oorspronkelijke huwelijk als laatste (stapel 2), dan krijg ik wel eenhoofdig ouderlijk gezag:
```
       			"gezag": [
       				{
       					"type": "EenhoofdigOuderlijkGezag",
       					"ouder": {
       						"burgerservicenummer": "000000012"
       					},
       					"minderjarige": {
       						"burgerservicenummer": "000000073"
       					}
       				}
       			]
```

De implementatie mag niet impliciet aannemen dat een eerdere relatie een lager stapel_nr heeft dan een recentere relatie.

**Comment by Patrick-4488** [comment]
De fix heeft het nog niet opgelost, er moet juist niet naar het volg nummer gekeken worden maar naar de datum zelf.
Ik heb een sortering op de lijst toegeveogd op basis van datumvoltrokken en nu gaat het wel in alle vormen goed (S&T, S&T ouder omgekeerd en S&T partners kinderen omgekeerd)
