### ISSUE TITLE
logging in haal-centraal-gezag aanpassen conform ECS en andere brp-api services

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#117]

**Comment by FrozenSync** [comment]
Gerelateerd aan #20 

Wordt opgepakt samen met #109

**Comment by FrozenSync** [comment]
Besproken voorstel om burgerservicenummers te vervangen met pl id haalde het niet, omdat bij deze oplossing `request.body` pas aan het einde van een request gevuld kan worden. Als er tussentijds een fout optreedt, blijft `request.body` leeg of wordt deze maar deels gevuld. Dit is niet wenselijk.

**Comment by FrozenSync** [comment]
[ecs-logging-java](https://github.com/elastic/ecs-logging-java) support nog geen _structured logging_, wat onder andere het maskeren van PII mogelijk maakt. Zie [issue](https://github.com/elastic/ecs-logging-java/issues/49). Deze issue is al bijna 5 jaar oud, dus het lijkt er niet op dat hier een oplossing komt op korte termijn.
