### ISSUE TITLE
Nieuwe deployment / release afspraken doorvoeren in gezag

### ISSUE THREAD

**Issue by Patrick-4488** [BRP-API/brp-api-gezag#126]
https://github.com/BRP-API/brp-shared/blob/docs/brp-api-lifecycle/docs/versioning-branching-strategie.md

**Comment by Patrick-4488** [comment]
Begin gemaakt met:
https://github.com/BRP-API/brp-api-gezag/blob/main/.github/workflows/release-acc.yml

loop tegen authorisatie problemen aan

**Comment by FrozenSync** [comment]
> Begin gemaakt met: https://github.com/BRP-API/brp-api-gezag/blob/main/.github/workflows/release-acc.yml
> 
> loop tegen authorisatie problemen aan

Een aantal opmerkingen:

- Bovenstaande workflow kan net zo goed lokaal worden uitgevoerd. Ik zie geen toegevoegde waarde om `git tag -a` te laten uitvoeren door de pipeline vs. een developer.
- Het lijkt mij niet de bedoeling dat deployment specifieke zaken worden geadministreerd in de git history. Zoiets past beter in een container registry. Daarin kan je OCI container images taggen met versies, maar ook met acc/lap/prd om de status in ops land bij te houden. Dat gecombineerd met een goede build tag, zoals een git commit SHA, en je bent in staat om hotfix branches aan te maken voor iedere omgeving. Deze workflow lijkt ook meer op de gebruikelijke workflow in DevOps land.
