### ISSUE TITLE
gezag met lege toelichting

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#152]
https://github.com/BRP-API/brp-api-gezag/blob/feature-2a2-adoptiefouders/features/gezag-minderjarige/2a.2-adoptiefouders.feature:60

Dit geeft
```
       				{
       					"type": "GezagNietTeBepalen",
       					"toelichting": ""
       				}
```

hier wordt geen toelichting gevuld. in het antwoordenmodel is er volgens mij voor elke route die tot GezagNietTeBepalen leidt een toelichting gevuld, dus had ik dat hier ook verwacht
waarom is het gezag hier niet te bepalen?

**Comment by Patrick-4488** [comment]
gezagmodule stopt direct bij v1.1 bij bepalen of persoon is ingeschreven in RNI omdat verblijfplaatst mist.
Vervolgens komt de route uit op 0 (want er is geen enkel antwoord op geen enkele vraag) maar met missende gegevens dit is geen scenario waar we met bepalen van toelichting op voorbereid waren.

Ik pas de code aan om met deze situaties goed om te gaan.
