### ISSUE TITLE
gegeven stappen voor gebeurtenis beschrijven met naam

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#161]
We hebben besloten dat we onderscheid maken tussen:
- gegevenstappen die een eigenschap van een persoon beschrijven. Die worden opgenomen met * en binnen de context van een persoon
- gegevenstappen die een gebeurtenis op een persoon beschrijven. Die worden opgenomen met * en bevatten de naam van de persoon.

Ook moet elke gegevenstap die een data tabel verwacht eindigen op "met de volgende gegevens"

Sommige gegevenstappen voldoen nog niet aan die regels en moeten worden hernoemd.

- in de features
  - [ ] #4
  - [ ] #8
  - [ ] #65 
  - [ ] #77 
  - [ ] #81 
  - [ ] #150
  - [ ] #151
- [ ] in de step implementatie

| huidige stap | wijzigen in |
|-- |-- |
| heeft gezag uitspraak|voor '(.*)' is een gerechtelijke uitspraak over het gezag gedaan met de volgende gegevens|
|staat onder curatele|'(.*)' is onder curatele gesteld|
| is overleden|'(.*)' is overleden|
|is geadopteerd door '(.*)' als ouder ([1-2])|'(.*)' is geadopteerd door '(.*)' als ouder ([1-2])|
|is geadopteerd door '(.*)' als ouder ([1-2]) met de volgende gegevens|'(.*)' is geadopteerd door '(.*)' als ouder ([1-2]) met de volgende gegevens|

**Comment by MelvLee** [comment]
geïmplementeerd in commit https://github.com/BRP-API/brp-api-gezag/commit/cd1f6dd3f3b0279cc6ab45e0e0b1da2cbb19a5b4
