### ISSUE TITLE
1.3 en 1.3a twijfel of controlle datum vestiging nederland correct en nodig is

### ISSUE THREAD

**Issue by Patrick-4488** [BRP-API/brp-api-gezag#204]
De code:
```
        if (datumVestigingInNederland == null
            || datumVestigingInNederland.isEmpty()
            || geboorteland.equals(GEBOORTELAND_CODE_NEDERLAND)
        ) {
            answer = V1_3A_NEE;
        } else {
            answer = V1_3A_JA;
        }
```
Deze code is vrijwel het zelfde in vraag 1.3. Vraag 1.3 en 1.3a alleen wordt er gecontrolleerd dat de persoon wel in nederland is geboren ipv. niet

De documentatie:
1.3a Is minderjarige in het buitenland geboren?
Geboorteland (01.03.30) is ongelijk aan 6030 (Nederland).

Verder argument de vraag is: `is de persoon geboren in het buitenland` de vraag is niet `is de persoon gevestigd in nederland`

**Comment by FrozenSync** [comment]
De controle is uit v1.3a gehaald door https://github.com/BRP-API/brp-api-gezag/issues/216. 

Voor v1.3 lijkt het mij correct.

**Comment by FrozenSync** [comment]
(1.3a) 
Een kind die in het buitenland is geboren zal bij verhuizing naar Nederland altijd een _datum vestiging in Nederland_ hebben. Dat betekent dat het voldoende is om een van de twee te controleren, omdat "is geboren in het buitenland" en "heeft datum vestiging in Nederland" altijd tegelijk voorkomen.

Het besluit om _datum vestiging in Nederland_ te verwijderen en de discussie eromheen zijn besproken in een dag start.

(1.3)
_Datum vestiging in Nederland_ wordt gebruikt om een remigratie te herkennen. Dit veld is dus nodig voor vraag 1.3.
