### ISSUE TITLE
Ongebruikte code verwijderen in gezag

### ISSUE THREAD

**Issue by Patrick-4488** [BRP-API/brp-api-gezag#211]
In gezag is ongebruikte code die kan worden opgeschoond zoals:

- alles in de package `soap`
- alles wat te maken heeft met nationaliteit (element 04)
- alles wat te maken heeft met overlijden (element 06)
- etc....

**Comment by FrozenSync** [comment]
Closed by https://github.com/BRP-API/brp-api-gezag/issues/260
