### ISSUE TITLE
Wat betekent staande huwelijk geboren?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#251]
In feature [2b.1](https://github.com/BRP-API/brp-api-gezag/blob/main/features/gezag-minderjarige/2b.1-is-staande-huwelijk-of-partnerschap-geboren.feature) staat in de intro-tekst:
> Wat betekend het wanneer een kind is geboren tijdens staande huwelijk of partnerschap?
>  1) Ja (staande huwelijk/partnerschap) -> GG: Ouder en echtgenoot/partner hebben gezamenlijk het gezag (1:253sa BW):
    a. meemoeders: kind tijdens huwelijk/gp geboren, is niet erkend en er is geen sprake van een verklaring onbekende donor of
    b. kind vóór 1 april 2014 geboren tijdens geregistreerd partnerschap van paren van verschillend geslacht en het kind is niet erkend.

Dat klinkt alsof alleen deze twee situaties gelden, maar dat blijkt niet uit de scenario's.

Wordt er iets gedaan met, of had er iets gedaan moeten zijn met:
a. check dat beide ouders vrouw zijn (meemoeders) en check ontbreken verklaring onbekende donor
b. check geboren voor 1 april 2014 en check ouders van verschillend geslacht

**Comment by Patrick-4488** [comment]
Klopt punt 1.b wordt op dit moment niets voor in de code gedaan inderdaad. 
Ik dacht dat hier al een issue voor gemaakt was maar die kan ik niet vinden.
Misschien kunnen we hier met dit issue naar kijken.

**Comment by fsamwel** [comment]
duidelijk, we gaan dit uitzoeken in het uitwerken van features
