### ISSUE TITLE
Wat leveren als persoon gevraagd is die geen gezag heeft

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#44]
De gezag api heeft in de response nu een structuur van eerst personen en per persoon het burgerservicenummer en het gezag.

Wanneer ik een persoon vraag die wel bestaat, maar geen gezagsrelaties heeft (bijv. meerderjarige zonder kinderen), dan verwacht ik wel de persoon te ontvangen met het burgerservicenummer en met een lege lijst gezag. Dat maakt het denk ik makkelijker voor de personen data service om de juiste gezagsrelaties bij de juiste personen te plaatsen, zeker wanneer er meerdere burgerservicenummer in 1 request zijn gevraagd.
@FrozenSync @Patrick-4488 @MelvLee hadden we hier al iets over afgesproken?

Bijvoorbeeld request:
```
{
    "burgerservicenummer": ["999970239"]
}
```
Geeft als response:
```
{
    "personen": []
}
```
Maar ik zou verwachten
```
{
    "personen": [
        {
            "burgerservicenummer": "999970239",
            "gezag": []
        }
    ]
}
```

**Comment by fsamwel** [comment]
voorstel is opgenomen in https://github.com/BRP-API/brp-api-gezag/pull/8

**Comment by FrozenSync** [comment]
Het voorstel hierboven wordt geïmplementeerd.
