### ISSUE TITLE
onverwacht gezag is niet te bepalen omdat minderjarige niet in Nederland woont

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#51]
in de feature in PR #4 geeft features/gezag-minderjarige/1.1-ingezetene-BRP.feature:80 als gezag:
```
{
  "type": "GezagNietTeBepalen",
  "toelichting": "gezag is niet te bepalen omdat minderjarige niet in Nederland woont."
}
```
Als ik de Gegeven stappen bekijk staat daar gemeente van inschrijving 0518 (ongelijk aan 1999). De persoon woont dus in Nederland. Ik verwacht daarom gezag wel bepaald kan worden. 
```
      En de persoon is ingeschreven op adres 'A1' met de volgende gegevens
      | naam                               | waarde                    |
      | gemeente van inschrijving (09.10)  | 0518                      |
```

Waar komt deze conclusie dat de persoon niet in Nederland woont vandaan?

**Comment by fsamwel** [comment]
Dit staat er bij het uitvoeren van de test in de verblijfplaats tabel. 

![Image](https://github.com/user-attachments/assets/ac77d63f-da29-4604-a8c2-8998c1a6bdc2)

**Comment by fsamwel** [comment]
na wat wijzigen en weer terugzetten tot oude versie krijg ik ineens een ander resultaat:
```
       			"gezag": [
       				{
       					"type": "GezagNietTeBepalen",
       					"toelichting": "gezag is niet te bepalen omdat bij de bepaling van bevoegdheid relevante gegevens ontbreken. Het gaat om de volgende gegevens: %s"
       				}
```

**Comment by FrozenSync** [comment]
De bovenstaande PR lijkt niet het oorspronkelijke probleem te hebben opgelost, namelijk "waarom kan gezag niet worden bepaald, terwijl ik dat wel verwacht?".

**Comment by Patrick-4488** [comment]
@FrozenSync @fsamwel 
Ik heb getest en wanneer in de feature de ouder 1 en ouder 2 een geboortedatum hebben slaagt de feature wel.
De feature valt nu hier op uit vanwege missende gegegevens.

**Comment by fsamwel** [comment]
> @FrozenSync @fsamwel Ik heb getest en wanneer in de feature de ouder 1 en ouder 2 een geboortedatum hebben slaagt de feature wel. De feature valt nu hier op uit vanwege missende gegegevens.

Ik heb nu geboortedatum bij de ouders toegevoegd: https://github.com/BRP-API/brp-api-gezag/pull/4/commits/34744ebef9689cb4c014c902617b0b4b69e77a46
