### ISSUE TITLE
ontbrekende gegeven wordt niet gevuld in toelichting

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#52]
Bijvoorbeeld in #4 features/gezag-minderjarige/1.1-ingezetene-BRP.feature:165
Hier is er geen verblijfplaats van de minderjarige opgenomen.

Ik krijg hier als gezag:
```
{
	"type": "GezagNietTeBepalen",
	"toelichting": "gezag is niet te bepalen omdat de volgende relevante gegevens ontbreken: %s"
}
```

Ik had verwacht dat in de toelichting %s zou zijn vervangen door het ontbrekende gegeven. In dit geval is dat bijvoorbeeld "gemeente van inschrijving"

**Comment by Patrick-4488** [comment]
is opgelost met #51

**Comment by FrozenSync** [comment]
Opgelost in PR https://github.com/BRP-API/brp-api-gezag/pull/63

**Comment by FrozenSync** [comment]
Aan de hand van de huidige implementatie:

```java
        var verblijfplaats = plPersoon.getVerblijfplaats();
        if (verblijfplaats == null) {
            gezagBepaling.addMissendeGegegevens("verblijfplaats van bevraagde persoon");
            return;
        }

        var gemeenteVanInschrijving = verblijfplaats.getGemeenteVanInschrijving();
        if (gemeenteVanInschrijving == null || gemeenteVanInschrijving.isEmpty()) {
            gezagBepaling.addMissendeGegegevens("gemeente van inschrijving van bevraagde persoon");
            return;
        }
```

wordt verblijfplaats als missende gegeven opgegeven wanneer verblijfplaats ontbreekt. Pas als verblijfplaats aanwezig is en gemeente van inschrijving ontbreekt, dan wordt gemeente van inschrijving als missende gegeven opgegeven. 

Is dit ook gewenst, @fsamwel ? Als het detail "verblijfplaats ontbreekt vs. gemeente van inschrijving ontbreekt" weinig toevoegt voor de burger, dan lijkt het mij simpeler om in beide gevallen gemeente van inschrijving op te geven als missende gegeven.

**Comment by fsamwel** [comment]
wat er komt maakt nu niet uit. "verblijfplaats" is zeker ook goed, wellicht beter dan "gemeente van inschrijving" als ontbrekend gegeven
