### ISSUE TITLE
Maak feature voor bepalen gezag over kinderen van (ex)partner

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#7]
Zet de bestaande feature voor gezag meerderjarige bij GG (gezamenlijk gezag over kinderen van partner) en V (gezag over kinderen van overleden ex-partner) om naar feature(s) voor de gezagsmodule.

Hiervoor moet gegeven worden omgezet naar data in de database (is nu gegeven wat de gezagsmodule levert) en request en response worden aangepast naar gezagsmodule.

**Comment by CathyDingemanse** [comment]
https://github.com/BRP-API/brp-api-gezag/pull/8

**Comment by Patrick-4488** [comment]
Implementatie met https://github.com/BRP-API/brp-api-gezag/pull/104
