### ISSUE TITLE
contradictie in toelichting route 32

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/brp-api-gezag#85]
Ja,Ja,Nee,Nee,,Ja,Twee_ouders,Nee_nooit,Nee,Voor,,Ja,,,Nee,,,32,N,Nee,Nee,Nee,Nee,3250,Ingezeten - minderjarig - categorie 11 en recentere gebeurtenis(sen) - heeft twee ouders - ouders ongehuwd/geen partnerschap - erkenning ongeboren vrucht voor 1-1-2023; wie gezag heeft valt niet te bepalen - beiden bevoegd - soort gezag is OG1 - ouder1 heeft gezag

Lijkt "gezag niet te bepalen" te zijn, maar dat blijkt niet uit de toelichting. Is het N of OG1?

**Comment by FrozenSync** [comment]
Bij route 32 hoort N uit te komen. De toelichting klopt dan inderdaad niet.

Het volgende gebeurt er bij route 32:

(vraag 2a.3)
- kind is niet erkend
  - ... op basis van aktenummers B, C, J en V in PL persoon
- ongeboren vrucht van kind is wel erkend
  - ... op basis van aktenummer A in PL persoon
- er heeft geen erkenning plaatsgevonden van ouder1 noch ouder2 na 01-01-2023
  - ... op basis van datum ingang familiebetrekking in PL ouder1/ouder2
- er heeft geen erkenning plaatsgevonden van ouder1 noch ouder2 voor 01-01-2023
  - ... op basis van aktenummers B, C, J en V in PL ouder1/ouder2
- kind is geboren voor 01-01-2023

In dit geval is de geboortemoeder theoretisch te bepalen, maar...

(vraag 4a.3)
- beide ouders zijn bevoegd

... is niet aan te wijzen welke van de twee ouders de geboortemoeder is.

**Comment by FrozenSync** [comment]
Er was ook een vraag op tafel gelegd over route 18.

**context**
Een juridische ouder. Rechtelijke uitspraak gezag aanwezig, maar daarna heeft er een significante gebeurtenis plaatsgevonden (ontkenning erkenning, adoptie of reparatiehuwelijk).

**vraag v2b.1**

- kind is niet in een staande relatie geboren, dus er valt geen relatie informatie op te halen die ons verder kan helpen

**vraag 4a.3**

- beide ouders leven en zijn bevoegd

In dit geval is er onvoldoende informatie om de ouder met gezag aan te wijzen.

**Comment by CathyDingemanse** [comment]
> Bij route 32 hoort N uit te komen. De toelichting klopt dan inderdaad niet.
> 
> Het volgende gebeurt er bij route 32:
> 
> **context** Twee juridische ouders die nooit een relatie (partnerschap/huwelijk) hebben gehad. Rechtelijke uitspraak gezag aanwezig, maar daarna heeft er een significante gebeurtenis plaatsgevonden (ontkenning erkenning, adoptie of reparatiehuwelijk).
> 
> **vraag 2a.3**
> 
> * kind is niet erkend
>   
>   * ... op basis van aktenummers B, C, J en V in PL persoon
> * ongeboren vrucht van kind is wel erkend
>   
>   * ... op basis van aktenummer A in PL persoon
> * er heeft geen erkenning plaatsgevonden van ouder1 noch ouder2 na 01-01-2023
>   
>   * ... op basis van datum ingang familiebetrekking in PL ouder1/ouder2
> * er heeft geen erkenning plaatsgevonden van ouder1 noch ouder2 voor 01-01-2023
>   
>   * ... op basis van aktenummers B, C, J en V in PL ouder1/ouder2
> * kind is geboren voor 01-01-2023
> 
> In dit geval is de geboortemoeder theoretisch te bepalen, maar...
> 
> **vraag 4a.3**
> 
> * beide ouders leven en zijn bevoegd
> 
> ... is niet aan te wijzen welke van de twee ouders de geboortemoeder is.

De toelichting is:
gezag kan niet worden bepaald omdat niet kan worden bepaald welke van de twee ouders de geboortemoeder is.

**Comment by CathyDingemanse** [comment]
> Er was ook een vraag op tafel gelegd over route 18.
> 
> **context** Een juridische ouder. Rechtelijke uitspraak gezag aanwezig, maar daarna heeft er een significante gebeurtenis plaatsgevonden (ontkenning erkenning, adoptie of reparatiehuwelijk).
> 
> **vraag v2b.1**
> 
> * kind is niet in een staande relatie geboren, dus er valt geen relatie informatie op te halen die ons verder kan helpen
> 
> **vraag 4a.3**
> 
> * beide ouders leven en zijn bevoegd
> 
> In dit geval is er onvoldoende informatie om de ouder met gezag aan te wijzen.

De toelichting wordt: 
gezag kan niet worden bepaald omdat er onvoldoende informatie is over een recente gebeurtenis (reparatiehuwelijk/ontkenning erkenning of adoptie)
