### ISSUE TITLE
tekst toelichting route 3e

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/brp-api-gezag#86]
Wat zou de toelichting hier moeten zijn?

**Comment by CathyDingemanse** [comment]
In overleg met Leroy tekst aangepast.
@FrozenSync voegt nog foutcode toe.

**Comment by FrozenSync** [comment]
Route 3e betekent dat het systeem onverwachts eruit is geklapt tijdens het beantwoorden van vraag 1.3 door een programmeerfout. Het is een technische fout. In die valt er niks zinnigs te zeggen in de context van de afleidingsregels.

**Comment by FrozenSync** [comment]
Completed in #87
