### ISSUE TITLE
features maken met testgevallen van Ts004: de Diana-acceptatietest

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#9]
Tests die voor acceptatietest (Schouwen en Toetsen) van de gezagsmodule zijn gemaakt door Diana omzetten in features/scenario's.

Wijzigingen zitten in https://github.com/BRP-API/brp-api-gezag/pull/3

- [X] Gegeven stappen exporteren uit de database
- [X] Als stappen maken
- [X] Dan stappen maken
- [x] Dan stappen aanpassen aan nieuwe response definitie.
- [x] Gegeven stappen corrigeren voor "minderjarigen" meerderjarig zijn geworden
- [x] Automation maken voor Als en Dan stappen

**Comment by fsamwel** [comment]
toelichtingen zijn ook toegevoegd, maar exacte teksten zullen nog wijzigen wanneer antwoordenmodel wordt aangepast. Zie https://github.com/BRP-API/brp-api-gezag/pull/13 en https://github.com/BRP-API/brp-api-gezag/issues/2

**Comment by FrozenSync** [comment]
Closed by https://github.com/BRP-API/brp-api-gezag/pull/3
